[package]
name = "jaime"
version = "0.3.0"
authors = ["Juan Ibiapina <juanibiapina@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xdg = "*"
serde = { version = "*", features = ["derive"] }
skim = "0.9.4"
rustyline = "9.0.0"
serde_yaml = "0.8.20"
failure = "0.1.8"
shlex = "1.1.0"
